#!/usr/bin/env bash

# Update packages
sudo apt update

# Install nginx
sudo apt install -y nginx

# Configure nginx to listen on port 80
sudo sed -i 's/# listen 80;/listen 80;/g' /etc/nginx/sites-available/default

# Start nginx service
sudo service nginx start

# Allow firewall to enable nginx server traffic
sudo ufw allow 'Nginx HTTP'

# Create custom 404 page
sudo sh -c 'echo "Ceci n'"'"'est pas une page" > /var/www/html/404.html'

# Configure nginx to use custom 404 page
sudo sed -i '/listen 80;/a \
\\n\terror_page 404 /404.html;\n\
\tlocation = /404.html {\n\
\t\troot /var/www/html;\n\
\t\tinternal;\n\
\t}' /etc/nginx/sites-available/default

# Restart nginx
sudo service nginx restart

echo "Nginx configured successfully with custom 404 page."
