#!/usr/bin/env bash
#display "Best School" 10 times using while loop
#and then 'hi' on a new line after line 9
myvar=1
while [ $myvar -le 10 ]
do
	echo "Best School"

if [ $myvar = 9 ]
then
	echo "Hi"
fi
	 myvar=$(( myvar +1 ))
done
