#!/usr/bin/env bash
#display "Best School" 10 times using while loop

myvar=1
while [ $myvar -le 10 ]
do
if [ $myvar = 4 ]
then
	echo "bad luck"
elif [ $myvar = 8 ]
then
	echo "good luck"
else
	echo "Best School"
fi
	 myvar=$(( myvar +1 ))
done
