#!/usr/bin/env bash
#display displays 4 and then bad luck from China for the 4th loop iteration
#displays 9 and then bad luck from Japan for the 9th loop iteration
#displays 17 and then bad luck from Italy for the 17th loop iteration

bad_luck_message() {
    case $1 in
        4)
        	echo "$1"
		echo "bad luck from China"
            ;;
        9)
        	echo "$1"  
		echo "bad luck from Japan"
            ;;
        17)
		echo "$1"
		echo "bad luck from Italy"
            ;;
        *)
            	echo "$1"
            ;;
    esac
}

# Loop to display numbers from 1 to 20
number=1
while [ $number -le 20 ]
do
    bad_luck_message $number
    ((number++))
done
