#!/usr/bin/env bash
#display displays 4 and then bad luck from China for the 4th loop iteration
#displays 9 and then bad luck from Japan for the 9th loop iteration
#displays 17 and then bad luck from Italy for the 17th loop iteration

myvar=1
while [ $myvar -le 20 ]
do
if [ $myvar = 4 ]
then
	echo "$myvar"
	echo "bad luck from China"
elif [ $myvar = 9 ]
then
	 echo "$myvar"
	echo "good luck from Japan"
elif [ $myvar = 17 ]
then
	echo "$myvar"
	echo "bad luck from Italy"
else
	echo "$myvar"
fi
	 myvar=$(( myvar +1 ))
done
