#!/usr/bin/env bash
#using the private key

#set the private key file
PRIVATE_KEY=~/.ssh/id_rsa.pub

#set the username
USERNAME=ubuntu

#set the server IP adress
HOST="35.153.50.197"

#connect to the server
ssh -i "$PRIVATE_KEY" "$USER_NAME"@"$SERVER_IP"
