#!/usr/bin/env bash

#setting private key name
PRIVATE_KEY="school"

#setting number of bits
BITS=4096

#setting passphrase
PASSPHRASE="betty"

#create key pair
ssh-keygen -t rsa -b "$BITS" -N "$PASSPHRASE" -f "$PRIVATE_KEY"
