#!/usr/bin/env bash

#set private key name
PRIVATE_KEY="school"

#set number of bits
BITS=4096

#set passphrase
PASSPHRASE="betty"

#create RSA key pair
ssh-keygen -t rsa -b "$BITS" -N "$PASSPHRASE" -f "$PRIVATE_KEY"
